# Empire Registry Auto-Maintenance — v2.0 Proactive Docs
# Automatically updates PROJECTS.md and flags stale tasks

param(
    [string]$Workspace = "C:\Users\spenc\.openclaw\workspace",
    [string]$TasksFile = "TASKS.md"
)

$tasksPath = Join-Path $Workspace $TasksFile
$projectsFile = Join-Path $Workspace "PROJECTS.md"

if (-not (Test-Path $tasksPath)) {
    Write-Verbose "No TASKS.md found"
    exit 0
}

$tasks = Get-Content $tasksPath
$projects = @{}
$staleTasks = @()

foreach ($line in $tasks) {
    if ($line -match "^##\s+(.+)$") {
        $project = $matches[1]
        if (-not $projects.ContainsKey($project)) {
            $projects[$project] = @{
                tasks = @()
                lastActive = (Get-Date)
            }
        }
    }
    elseif ($line -match "^-\s+\[.\]\s+(.+)$") {
        $task = $matches[1]
        $checked = $line.Contains("[x]")
        if ($project) {
            $projects[$project].tasks += @{ title = $task; done = $checked }
            $projects[$project].lastActive = Get-Date
        }
    }
}

# Identify stale projects (no activity > 7 days)
$now = Get-Date
foreach ($p in $projects.Keys) {
    $daysInactive = ($now - $projects[$p].lastActive).Days
    if ($daysInactive -gt 7) {
        $staleTasks += "$p (inactive $daysInactive days)"
    }
}

# Generate PROJECTS.md
$content = "# Projects`n`nAuto-generated by Proactive Agent`n`n"
foreach ($p in $projects.Keys) {
    $proj = $projects[$p]
    $active = $proj.lastActive.ToString('yyyy-MM-dd')
    $todoCount = ($proj.tasks | Where-Object { -not $_.done }).Count
    $doneCount = ($proj.tasks | Where-Object { $_.done }).Count
    $content += "## $p`n- Last active: $active`n- Tasks: $todoCount todo, $doneCount done`n`n"
}

if ($staleTasks.Count -gt 0) {
    $content += "## Stale Projects`n"
    foreach ($s in $staleTasks) {
        $content += "- $s`n"
    }
}

$content | Out-File -FilePath $projectsFile -Encoding UTF8
Write-Host "Projects registry updated: $($projects.Count) projects, $($staleTasks.Count) stale"
